[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.16"
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
mainnet  = "${ALCHEMY_RPC_URL_MAINNET}"
goerli   = "${ALCHEMY_RPC_URL_GOERLI}"
polygon  = "${ALCHEMY_RPC_URL_POLYGON}"
mumbai   = "${ALCHEMY_RPC_URL_MUMBAI}"
optimism = "${ALCHEMY_RPC_URL_OPTIMISM}"
opt-go   = "${ALCHEMY_RPC_URL_OPT_GOERLI}"
anvil    = "http://localhost:8545"

[etherscan]

[fmt]
line_length = 120
