[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.16"

[rpc_endpoints]
goerli = "${ALCHEMY_RPC_URL_GOERLI}"
mumbai = "${ALCHEMY_RPC_URL_MUMBAI}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
